### ISSUE TITLE
gen_data for measles order

### ISSUE THREAD

**Issue by aspina7** [R4EPI/msfdict#12]
pat posted in https://github.com/R4EPI/sitrep/issues/223

> Very minor but the generated dataset is in an unusual order ( just not what you'd expect )
> sitrep/inst/rmarkdown/templates/measles_outbreak/skeleton/skeleton.Rmd
> 
> Line 140 in 9b44e40
> 
>  linelist_raw <- gen_data("Measles") 
> 
> Alex: yeah unsure when this happened but need to look in to.

**Comment by aspina7** [comment]
this is because the xlsx dictionaries we were sent were organised like this, I just need to sort in excel by `data element name` and then hopefully all this egen_001 thing will get it in at least close to the right order... 
if not then wont fit within this contract. 
@pbkeating fyi

**Comment by pbkeating** [comment]
OK, no worries.. very minor

**Comment by aspina7** [comment]
sorted!
