### ISSUE TITLE
survey dictionary odk issues

### ISSUE THREAD

**Issue by aspina7** [R4EPI/msfdict#16]
@pbkeating putting this in an issue for now as am merging the PR so dont want to loose

- [x] `treatment_delay` - restriction should be `${care_illness_last} = "yes"`, updated on github version 
- [x] `reason_first_hf_selected` restriction should be `${place_first_hf} = "other" or  ${place_first_hf} = "hospital" or ${place_first_hf} = "primary_health_centre" or ${place_first_hf} = "primary_health_unit"`, updated on github version 

variable naming consistency between vaccination and nutrition: 
- [x] `number_children` in nutrition and `children_count` in vaccination - should choose one and be consistent
- [x] `num_qua**n**d_penta_woc` should be `num_quad_penta_woc` - updated on github version (otherwise ruins iteration) 
- [x] `num_poliodrop_hf_woc` and `num_poliodrop_camp_woc` should be changed to remove the `num_` to be consistent with others  - updated on github version (otherwise ruins iteration)

**Comment by pbkeating** [comment]
Updated treatment_delay and reason_first_hf_selected
Changed children_count to be number_children
Changed  num_quand... to be num_quad

Not clear on last point since we ask how many times for the other vaccines and we have num_ before?
P

**Comment by aspina7** [comment]
> - [x] num_poliodrop_hf_woc and num_poliodrop_camp_woc should be changed to remove the num_ to be consistent with others - updated on github version (otherwise ruins iteration)
>> Not clear on last point since we ask how many times for the other vaccines and we have num_ before? 

but you arent consistent in your use of `num_` prefix. See from [this line onwards](https://github.com/R4EPI/epidict/blob/master/R/gen_msf_data.R#L661) - specifically ... all the vaccines that have multiple "number of doses" questions dont have num_ infront, except for poliodrop.

**Comment by aspina7** [comment]
@pbkeating
> * [x]  `number_children` in nutrition and `children_count` in vaccination
>> Changed children_count to be number_children


need to swap to `number_children` in vaccination short too pls

**Comment by pbkeating** [comment]
Wasn’t clear on this point. I noticed that it should have been number_children in the repeat_count column of the short VCS. Am assuming that’s what you meant and that’s what I updated.
P

**Comment by aspina7** [comment]
@pbkeating closing this now - pls doublecheck you did all the box ticking above thankings kisses
