### ISSUE TITLE
Change package name to epidict

### ISSUE THREAD

**Issue by zkamvar** [R4EPI/msfdict#2]
The name {msfdict} implies that these are only dictionaries for MSF. If we change it to {epidict}, then we could allow further dictionaries from orgs like WHO AFRO

Steps:

 - [x] search replace msfdict with epidict
 - [ ] rename dictionary files to have the MSF prefix
 - [ ] add function called `get_dict()` and make it general for any dictionary by adding `org` argument, setting it to default for MSF.
 - [ ] add `org = "MSF"` for the `gen_data()` function.
 - [ ] replace insides of `msf_*()` to use `gen_dict()`

**Comment by aspina7** [comment]
Like it

**Comment by zkamvar** [comment]
fixed in #5
